<a href="https://colab.research.google.com/github/yaesur/python_team/blob/main/4%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8(202010678%20%ED%91%9C%EC%84%B1%EB%AF%BC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
#안녕하세요
##안녕하세요
###안녕하세요
####안녕하세요

위 셀의 코드를 실행하려면 셀을 클릭하여 선택한 후 코드 왼쪽의 실행 버튼을 누르거나 단축키"Command/Ctrl+Enter"를 사용하세요.
셀을 클릭하면 코드 수정을 바로 시작할 수 있습니다.

### 1. 이것은 마크다운 제목입니다
일반적인 글은 **마크다운**으로 쓰는 게 편해요.

### 2. 이것은 HTML 효과입니다
마크다운은 <span style="color: blue; font-weight: bold;">글자 색상 변경</span>이 안 되지만, HTML을 섞어 쓰면 가능하죠!

<div align="right">이 문장은 HTML 태그를 사용해 오른쪽으로 정렬했습니다.</div>

$\sqrt{2}$
$x^2 + y^2$

In [34]:
seconds_in_a_week =24*60*7
seconds_in_a_week

10080

#안녕하세요
###안녕하세요
###안녕하세요
####안녕하세요

**혼공분석**
*혼공 분석*
~~취소선~~
>혼공분석
* 혼공분석
- 혼공분석

In [35]:
import gdown
gdown.download('http://bit.ly/3eecMKZ', '남산도서관 장서 대출목록(2021년 04월).csv', quiet=False)

Downloading...
From: http://bit.ly/3eecMKZ
To: /content/남산도서관 장서 대출목록(2021년 04월).csv
100%|██████████| 58.1M/58.1M [00:00<00:00, 128MB/s]

'남산도서관 장서 대출목록(2021년 04월).csv'

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
# 파이썬으로 CSV 파일 출력하기
with open('남산도서관 장서 대출목록 (2021년 04월).csv', mode='rb') as f:
      d = f.readline()
      print(f.readline())

b'"1","\xc0\xce\xb0\xf8\xc1\xf6\xb4\xc9\xb0\xfa \xc8\xeb","\xb1\xe8\xb5\xbf\xc8\xc6 \xc1\xf6\xc0\xbd","\xb9\xce\xc0\xbd\xbb\xe7","2021","9788937444319","","","","","1","0","2021-03-19",\n'

In [38]:
#파일 인코딩 형식 확인하기: chardet.detect()함수
import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv', mode='rb') as f :
    d = f.readline()
print(chardet.detect(d))

{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [39]:
with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR') as f :
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

In [40]:
import pandas as pd

df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR', low_memory=False)

In [41]:
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr', low_memory=False)

In [42]:
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [43]:
df.to_csv('ns_202104.csv')

In [44]:
with open('ns_202104.csv') as f:
    for i in range(3):
        print(f.readline(), end= ' ')

# end='' 없을 때
with open('ns_202104.csv') as f:
    for i in range(3):
        print(f.readline())

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
 0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,
 1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,
 ,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13

0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,

1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,

In [45]:
ns_df = pd.read_csv('ns_202104.csv',index_col=0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [46]:
#index_col=() 없을 때
ns_df = pd.read_csv('ns_202104.csv', low_memory=False)
ns_df.head()

,Unnamed: 0,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [47]:
df.to_csv('ns_202104.csv', index=False)

In [48]:
# xlsxwriter 패키지 설치.
!pip install xlsxwriter

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

In [32]:
ns_df.to_excel('ns_202104.xlsx', index=False, engine='xlsxwriter')